# Build stage
FROM node:22-alpine AS builder

WORKDIR /rr-client

# Copy package files
COPY ./client/package*.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY ./client .

# Build arguments
ARG VITE_APP_PORT
ARG VITE_APP_ENV
ARG VITE_APP_APP_NAME
ARG VITE_APP_SERVER_URL
ARG VITE_APP_PORTAL_URL

ENV VITE_APP_PORT=$VITE_APP_PORT
ENV VITE_APP_ENV=$VITE_APP_ENV
ENV VITE_APP_APP_NAME=$VITE_APP_APP_NAME
ENV VITE_APP_SERVER_URL=$VITE_APP_SERVER_URL
ENV VITE_APP_PORTAL_URL=$VITE_APP_PORTAL_URL

# Build
RUN npm run build


# Production stage
FROM nginx:alpine

COPY --from=builder /rr-client/dist /usr/share/nginx/html

RUN echo 'server { \
    listen 3000; \
    server_name _; \
    root /usr/share/nginx/html; \
    index index.html; \
    location / { \
    try_files $uri $uri/ /index.html; \
    } \
    }' > /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]