# -------- Build Stage --------
FROM node:22-alpine AS builder

WORKDIR /rr-server

# Install dependencies
COPY ./server/package*.json ./
RUN npm ci

# Copy source
COPY ./server .

# Remove dev dependencies
RUN npm prune --omit=dev


# -------- Production Stage --------
FROM node:22-alpine

WORKDIR /rr-server

# Copy from builder
COPY --from=builder /rr-server /rr-server

# Security
USER node

ENV NODE_ENV=production

EXPOSE 5000

CMD ["node", "server.js"]