# Build stage
FROM node:22-alpine AS builder

WORKDIR /rr-admin

COPY ./admin/package*.json ./
RUN npm ci

COPY ./admin .

ARG VITE_APP_ADMIN_NAME
ARG VITE_APP_SERVER_URL
ARG VITE_APP_ADMIN_URL

ENV VITE_APP_ADMIN_NAME=$VITE_APP_ADMIN_NAME
ENV VITE_APP_SERVER_URL=$VITE_APP_SERVER_URL
ENV VITE_APP_ADMIN_URL=$VITE_APP_ADMIN_URL

RUN npm run build


# Production stage
FROM nginx:alpine

COPY --from=builder /rr-admin/dist /usr/share/nginx/html

RUN echo 'server { \
    listen 3001; \
    server_name _; \
    root /usr/share/nginx/html; \
    index index.html; \
    location / { \
    try_files $uri $uri/ /index.html; \
    } \
    }' > /etc/nginx/conf.d/default.conf

EXPOSE 3001

CMD ["nginx", "-g", "daemon off;"]