const PASSWORD_MIN_LENGTH = 8;
const PASSWORD_MAX_LENGTH = 22;
const PASSWORD_ALLOWED_PATTERN = "^[a-zA-Z0-9@#$%^&+=!*-_.]{8,22}$";
const PASSWORD_ALLOWED_REGEX = new RegExp(PASSWORD_ALLOWED_PATTERN);
const PASSWORD_POLICY_MESSAGE = `Password must be ${PASSWORD_MIN_LENGTH} to ${PASSWORD_MAX_LENGTH} characters long.`;

module.exports = {
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  PASSWORD_ALLOWED_PATTERN,
  PASSWORD_ALLOWED_REGEX,
  PASSWORD_POLICY_MESSAGE,
};
